### ISSUE TITLE
Phoenix 1.6 ready?

### ISSUE THREAD

**Issue by razz-matazz** [surface-ui/surface_catalogue#25]
Hello,

I have created a new app with phoenix 1.6 and did as mentioned in "Installation", but I run into following error:
```
mix phx.server
==> surface_catalogue
Compiling 19 files (.ex)

== Compilation error in file lib/surface/catalogue/server.ex ==
** (ArgumentError) unknown live option :layout.

Supported options include: :container, :as, :metadata, :private.

Got: [layout: {Surface.Catalogue.LayoutView, :root}]

    (phoenix_live_view 0.16.4) lib/phoenix_live_view/router.ex:386: anonymous fn/1 in Phoenix.LiveView.Router.validate_live_opts!/1
    (elixir 1.12.3) lib/enum.ex:930: Enum."-each/2-lists^foreach/1-0-"/2
    (phoenix_live_view 0.16.4) lib/phoenix_live_view/router.ex:360: Phoenix.LiveView.Router.validate_live_opts!/1
    (phoenix_live_view 0.16.4) lib/phoenix_live_view/router.ex:340: Phoenix.LiveView.Router.__live__/4
    lib/surface/catalogue/server.ex:23: (module)
    lib/surface/catalogue/server.ex:13: (module)
    (stdlib 3.16) erl_eval.erl:685: :erl_eval.do_apply/6
could not compile dependency :surface_catalogue, "mix compile" failed. You can recompile this dependency with "mix deps.compile surface_catalogue", update it with "mix deps.update surface_catalogue" or clean it with "mix deps.clean surface_catalogue"
```

**Comment by msaraiva** [comment]
Fixed in b5e41520fb987a62ddf566cff7b572f650ac975d.
